# Generated by Django 6.0.6 on 2026-06-23 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_description', models.TextField(verbose_name='Опис проблеми')),
                ('repair_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Вартість ремонту')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Дата звіту')),
                ('date_fixed', models.DateTimeField(blank=True, null=True, verbose_name='Дата виправлення')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='inventory.equipment')),
            ],
        ),
    ]
